spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/transactiondb
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true